DROP DATABASE IF EXISTS ;
CREATE DATABASE ;

USE ;

CREATE TABLE (
  -- id INT NOT NULL,
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 VARCHAR(30) NOT NULL,
   VARCHAR(100) NOT NULL,
   INT NOT NULL,
  BOOLEAN
);

CREATE TABLE (
  id INT NOT NULL,
  -- id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 VARCHAR(30) NOT NULL
);