DROP DATABASE IF EXISTS movie_db;
CREATE DATABASE movie_db;

USE movie_db;

CREATE TABLE movies(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 movie_name VARCHAR(100)
);

CREATE TABLE reviews(
  id INT NOT NULL,
  movie_id INT NOT NULL,
  review TEXT NOT NULL
);